id: I4EBDD47B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T11:11:23+00:00'
last_modified: '2022-06-10T04:52:03.425456+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W21888
  title: གཏེར་ཆོས། ཀུན་བཟང་བདེ་སྐྱོང་དབང་མོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1DA8:
      image_group_id: I1983
      title: ''
      total_pages: 517
      order: 1
      base_file: 1DA8.txt
    C8C3:
      image_group_id: I1984
      title: ''
      total_pages: 587
      order: 2
      base_file: C8C3.txt
    '5444':
      image_group_id: I1985
      title: ''
      total_pages: 507
      order: 3
      base_file: 5444.txt
    14B9:
      image_group_id: I1986
      title: ''
      total_pages: 551
      order: 4
      base_file: 14B9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
