id: P000353
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 2021-12-16 15:35:31.738612
source_metadata:
  id: bdr:W21888
  title: གཏེར་ཆོས། ཀུན་བཟང་བདེ་སྐྱོང་དབང་མོ།
  author: ''
  volumes:
    67016e904ee44b43a971401ca561daec:
      image_group_id: I1983
      title: ''
      volume_number: 1
      total_pages: 517
    805134ef23ee46dca3ce35eb7688f459:
      image_group_id: I1984
      title: ''
      volume_number: 2
      total_pages: 587
    1614b2fc35624495bc26cb2c4f08cbca:
      image_group_id: I1985
      title: ''
      volume_number: 3
      total_pages: 507
    6ecdb0f42fdf4ed3adda14e946c1b7db:
      image_group_id: I1986
      title: ''
      volume_number: 4
      total_pages: 551
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
